name: functional

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: unlock secrets
        id: unlock_secrets
        uses: someara/action-git-crypt-unlock@main
        env:
          GPG_PRIVATE_KEY: "AEdJVENSWVBUS0VZAAAAAgAAAAAAAAABAAAABAAAAAAAAAADAAAAIP3gM8cKGw3QJfx2/3RMCU3HOvHyo5hFuEc7GNNln02FAAAABQAAAECAsdWf/f1KgNtJUB48uX1z0qMOOY0k9xCNPieiiAKKbjj+7vd3iHvTTzwOxa7hSpgIvtQTtbiN5PlP+Yw6+0rIAAAAAA=="
          GPG_KEY_GRIP: "4D72A10E4079686A0308742AC0FAAFB27A3C270E"
          GPG_KEY_PASS: "abc123"

      - name: print testfile
        id: print_testfile
        run: |
          cat test/testfile
