name: functional

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: unlock secrets
        id: unlock_secrets
        uses: someara/action-git-crypt-unlock@main
        env:
          GPG_PRIVATE_KEY: "lDsEX5tQcBYJKwYBBAHaRw8BAQdAU4QbcJW7gJjs/rkXcB/KyMQKDM5e9WiHlAlzuI70M5X/AGUAR05VAbQfZGVtb2xhYiA8ZGVtb2xhYkBjb21wdXRlcnMuYml6PoiNBBMWCAA1FiEEGIlXw5fkwx7JyYpPhvityAz7Hk8FAl+bUHACGwMFCQABUYACCwkCFQgCFgICHgECF4AACgkQhvityAz7Hk86xwEA81dcCRWX2HMniubcwtVtxaFbDmecZ8CeB+TyMEzYqQIBAPIubjdmErQgwnHeARc7kFAZ/Cp4KWuvL26grN2BZ0IOnIsEX5tQcBIKKwYBBAGXVQEFAQEHQHSjJjoRpwKc2zzktn/39bzpjf70fN8PVALuVk0ZKhQNAwEIB/4HAwJm6WTMH6eeHu2Qf0Fmyv05G6T/AxioWwzF5qjRXrjpQwjQKObLGJZDyvTlJ+KerLBn95LOlYeu3qJziFj7iVIQFrRjMy8/zRipGgef6sSmiH4EGBYIACYWIQQYiVfDl+TDHsnJik+G+K3IDPseTwUCX5tQcAIbDAUJAAFRgAAKCRCG+K3IDPseT5QFAP90WEanWkkElwspUKsQYGEkJWclkr25IkDGQaq0t5qxFAEAom9vEIXY4tTFXqla/lYLsQruDQyCL5UbAUeRCYPRSAyciwRfm2aDEgorBgEEAZdVAQUBAQdAD7HVBjESi2Q51k3GFOXZ/Fm/jSeyMx0f0aFd8pMFOzEDAQgH/gcDAk6JK/99EPNu7fl16CRY3tkIH0r/29ElSUacDnKJ373AGMzetqKW6jAkGrz3LSo2YifCLYxP2RNllahcXpyZYSa+EWx4PXDqm1hFvVRn6a6IfgQYFggAJhYhBBiJV8OX5MMeycmKT4b4rcgM+x5PBQJfm2aDAhsMBQkAAVGAAAoJEIb4rcgM+x5PddMBAKsTjpjIbWdkx1nw+yjD3BbYDDAvYoVRl/csmiZoOb6KAQD46ib4t6+NsUe5hdRGjfdugUAxY9L8prFO/GQRq9hnCpyLBF+bZwkSCisGAQQBl1UBBQEBB0BA4ThA7ySSIhH3ORYrLy4PqsxhWl33S49pYMGp7VA5EAMBCAf+BwMCr0HBnmsSlortmsFfKb3JG5ZesoFkKcbxDFvw5SjEckFy7DAU4l5VNAPKj3fYgAlA20lK0JJJ1pg++03tdLN9IAKjyzl6943B7CW3T0YjUYh+BBgWCAAmFiEEGIlXw5fkwx7JyYpPhvityAz7Hk8FAl+bZwkCGwwFCQABUYAACgkQhvityAz7Hk+TfQD/Xdg0cD1lm4fGpvVoC9Xzu2q7oEI6CkTQ6/lYA9wANBUBAO6gz3dlkXh6u8QMIufp9fwV9go4Gr1TUH8nm4qfbBMPnIsEX5txNRIKKwYBBAGXVQEFAQEHQI/RNMmGJhqfDmvbjroB4KOnorWOVxW72+pDzrZxx6kYAwEIB/4HAwKlNYbLxK4me+3tQzT7IRUKA/YPvY89tURPhE34zjRleT89ckqQ2N9c7TfKh/i6f3/Zk9sWGjuEeV5pe50tWay7KpSquXUepXsXL2TQXy77iH4EGBYIACYWIQQYiVfDl+TDHsnJik+G+K3IDPseTwUCX5txNQIbDAUJAAFRgAAKCRCG+K3IDPseT6IzAQCYBNyo2j31vOCHYHIbgyEhog9OZ5aOXjRmtRSP04M5pgEAxDYoGVwysj70ghdp/Sg/FzJRv6tCrQW5vzu1zZ6Htg+ciwRfm3IYEgorBgEEAZdVAQUBAQdAD9x9w1GjWGcPJSSw2k8uc7AZDteNF9Y6xQhXzihtFmYDAQgH/gcDAoX7eTfxXg3O7dfz3Gr2nD3/VeSOJlhJnoHyPUHV1FX8v7A5HV0JcSjSAcepl/WpMlmBJ2gp23ggEVPoH/y4hlkhwWQ6WCiwiJU1xRJQwmKIfgQYFggAJhYhBBiJV8OX5MMeycmKT4b4rcgM+x5PBQJfm3IYAhsMBQkAAVGAAAoJEIb4rcgM+x5P56cBAOO4hNt0YBawM27/MLGVytUXXgJKrKZphNoSiDp2jrz5AP9vY3vzKyrpR8bbD1KDjNuzH5D7w90IktEbibd0On/WCpyLBF+bdw0SCisGAQQBl1UBBQEBB0BKStMoftHoEOnY2XvbMZYNCf11NFj8xa3CmyJPqadbIgMBCAf+BwMCTmMJ4ctmJUftCmOSOf8Pxydiw9lMPtGYTxtGTlDl1TTs0xyh6nqmHf+/HF2gKiF1JudndqW8rXHJSGVfFYGWlifGql1ssrZh8rixF7sBb4h+BBgWCAAmFiEEGIlXw5fkwx7JyYpPhvityAz7Hk8FAl+bdw0CGwwFCQABUYAACgkQhvityAz7Hk8zLQEAuEv1RAXJIGiLrGZUFDOJ5XbpmFJ7Pd0LOKBJ8XhanawA/0BoBPQBj4QbyuwftkpAnlub+TKVAdQSaJqkL7fWCFEDnIsEX5t9FhIKKwYBBAGXVQEFAQEHQAthtyczYf326/IASUlN3ULwBB/ThpPo5zP0ODMANs5OAwEIB/4HAwKfXH1Z1Qm4++2BPSBQDsA2v0K/9mSNBhwjSDbiVW14mrBPDwUNvfY6MbA6jbBoXrwHkt7cw+eMmzsP34nGJ1QdkyWa59Vw0W4PzrTCt73xiH4EGBYIACYWIQQYiVfDl+TDHsnJik+G+K3IDPseTwUCX5t9FgIbDAUJAAFRgAAKCRCG+K3IDPseT0AEAP9lQCPpxT6XcqrLe4gr0A320C38LyshNuAJTT8FHxvhiwD/cinTmWF2R4QCh2HMMKedH7mSa2WWA3WySRbBoof/EwM="
          GPG_KEY_GRIP: "2D8E593F5372A65A4B355B579E81E6FE9D0AF08F"
          GPG_KEY_PASS: "abc123"

      - name: print testfile
        id: print_testfile
        run: |
          cat test/testfile
