name: functional

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: unlock secrets
        id: unlock_secrets
        uses: someara/action-git-crypt-unlock@main
        env:
          GPG_PRIVATE_KEY: "lDsEX5tQcBYJKwYBBAHaRw8BAQdAU4QbcJW7gJjs/rkXcB/KyMQKDM5e9WiHlAlzuI70M5X/AGUAR05VAbQfZGVtb2xhYiA8ZGVtb2xhYkBjb21wdXRlcnMuYml6PoiNBBMWCAA1FiEEGIlXw5fkwx7JyYpPhvityAz7Hk8FAl+bUHACGwMFCQABUYACCwkCFQgCFgICHgECF4AACgkQhvityAz7Hk86xwEA81dcCRWX2HMniubcwtVtxaFbDmecZ8CeB+TyMEzYqQIBAPIubjdmErQgwnHeARc7kFAZ/Cp4KWuvL26grN2BZ0IOnIsEX5tQcBIKKwYBBAGXVQEFAQEHQHSjJjoRpwKc2zzktn/39bzpjf70fN8PVALuVk0ZKhQNAwEIB/4HAwIKIy/vkH60cu2BMMlfZugkFvtZ3odu7CT8RwPTzm1ZbOyrcSVLlFCv6vJas4eXS17jqKApfLnRcb1XBdRRaOe9aNDaQ8UMuTotTExVtxVaiH4EGBYIACYWIQQYiVfDl+TDHsnJik+G+K3IDPseTwUCX5tQcAIbDAUJAAFRgAAKCRCG+K3IDPseT5QFAP90WEanWkkElwspUKsQYGEkJWclkr25IkDGQaq0t5qxFAEAom9vEIXY4tTFXqla/lYLsQruDQyCL5UbAUeRCYPRSAyciwRfm2aDEgorBgEEAZdVAQUBAQdAD7HVBjESi2Q51k3GFOXZ/Fm/jSeyMx0f0aFd8pMFOzEDAQgH/gcDArPWtxzFplys7U41gUBPQDAldnx7m73fOcvnUtVuwtn9b0MF2p2P5IGxloAjJTgI2uWxrXqf9nBNq5VshibkR997I5A5W2rtd6/bkkSKfL2IfgQYFggAJhYhBBiJV8OX5MMeycmKT4b4rcgM+x5PBQJfm2aDAhsMBQkAAVGAAAoJEIb4rcgM+x5PddMBAKsTjpjIbWdkx1nw+yjD3BbYDDAvYoVRl/csmiZoOb6KAQD46ib4t6+NsUe5hdRGjfdugUAxY9L8prFO/GQRq9hnCpyLBF+bZwkSCisGAQQBl1UBBQEBB0BA4ThA7ySSIhH3ORYrLy4PqsxhWl33S49pYMGp7VA5EAMBCAf+BwMCwiAribodla/tnd6QijG6FSwISV3wy/oQd3HoqGWL0ldF7HBQpaz3DUv9zsTVjfeMfbSA9Gcp69MbOXnZPanspfv9E78O78SeVGu1JyXZ2Yh+BBgWCAAmFiEEGIlXw5fkwx7JyYpPhvityAz7Hk8FAl+bZwkCGwwFCQABUYAACgkQhvityAz7Hk+TfQD/Xdg0cD1lm4fGpvVoC9Xzu2q7oEI6CkTQ6/lYA9wANBUBAO6gz3dlkXh6u8QMIufp9fwV9go4Gr1TUH8nm4qfbBMPnIsEX5txNRIKKwYBBAGXVQEFAQEHQI/RNMmGJhqfDmvbjroB4KOnorWOVxW72+pDzrZxx6kYAwEIB/4HAwKLB3CxkNqUCO0BI72Cp8zegMVB0v8EDHzbLTqCF3SDd+TOsXeYyzLxDgsUJAt9vZP5wyd6YafWrkhqkFMw1xBZv/cDRqzEjKPeHszL+HvdiH4EGBYIACYWIQQYiVfDl+TDHsnJik+G+K3IDPseTwUCX5txNQIbDAUJAAFRgAAKCRCG+K3IDPseT6IzAQCYBNyo2j31vOCHYHIbgyEhog9OZ5aOXjRmtRSP04M5pgEAxDYoGVwysj70ghdp/Sg/FzJRv6tCrQW5vzu1zZ6Htg+ciwRfm3IYEgorBgEEAZdVAQUBAQdAD9x9w1GjWGcPJSSw2k8uc7AZDteNF9Y6xQhXzihtFmYDAQgH/gcDAsk0m8JCDYI67ZsfLdQQU4ISWvlrDY8gvx1bxelb6CkLgqaUMj43tNJkckxkpEL3Hh/J6hlwaTD2yI5FW40Z8o2bZML5n5Oqj4juZTEbGNOIfgQYFggAJhYhBBiJV8OX5MMeycmKT4b4rcgM+x5PBQJfm3IYAhsMBQkAAVGAAAoJEIb4rcgM+x5P56cBAOO4hNt0YBawM27/MLGVytUXXgJKrKZphNoSiDp2jrz5AP9vY3vzKyrpR8bbD1KDjNuzH5D7w90IktEbibd0On/WCpyLBF+bdw0SCisGAQQBl1UBBQEBB0BKStMoftHoEOnY2XvbMZYNCf11NFj8xa3CmyJPqadbIgMBCAf+BwMCnjba2+vtl2ztggfnyewUHCWm3BZ7JAoIdCFgGxSGBOOyuq8qARa4Ev09gUf6+F0WTkDv0iBaktGV2A/T7hDAAq0saFyNR2A9NlEk0OIBhYh+BBgWCAAmFiEEGIlXw5fkwx7JyYpPhvityAz7Hk8FAl+bdw0CGwwFCQABUYAACgkQhvityAz7Hk8zLQEAuEv1RAXJIGiLrGZUFDOJ5XbpmFJ7Pd0LOKBJ8XhanawA/0BoBPQBj4QbyuwftkpAnlub+TKVAdQSaJqkL7fWCFED"
          GPG_KEY_GRIP: "9304F8E2BCC519F2431FD4B8F10734FA9B9552AD"
          GPG_KEY_PASS: "abc123"

      - name: print testfile
        id: print_testfile
        run: |
          cat test/testfile
