name: functional

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: unlock secrets
        id: unlock_secrets
        uses: someara/action-git-crypt-unlock@main
        env:
          GPG_PRIVATE_KEY: "LS0tLS1CRUdJTiBQR1AgUFJJVkFURSBLRVkgQkxPQ0stLS0tLQoKbERzRVg1dFFjQllKS3dZQkJBSGFSdzhCQVFkQVU0UWJjSlc3Z0pqcy9ya1hjQi9LeU1RS0RNNWU5V2lIbEFsegp1STcwTTVYL0FHVUFSMDVWQWJRZlpHVnRiMnhoWWlBOFpHVnRiMnhoWWtCamIyMXdkWFJsY25NdVltbDZQb2lOCkJCTVdDQUExRmlFRUdJbFh3NWZrd3g3SnlZcFBodml0eUF6N0hrOEZBbCtiVUhBQ0d3TUZDUUFCVVlBQ0N3a0MKRlFnQ0ZnSUNIZ0VDRjRBQUNna1Fodml0eUF6N0hrODZ4d0VBODFkY0NSV1gySE1uaXViY3d0VnR4YUZiRG1lYwpaOENlQitUeU1FellxUUlCQVBJdWJqZG1FclFnd25IZUFSYzdrRkFaL0NwNEtXdXZMMjZnck4yQlowSU9uSXNFClg1dFFjQklLS3dZQkJBR1hWUUVGQVFFSFFIU2pKam9ScHdLYzJ6emt0bi8zOWJ6cGpmNzBmTjhQVkFMdVZrMFoKS2hRTkF3RUlCLzRIQXdKNmhmaUgxa2ZRSWUxMDRCdDA5RFF5ZTdOQTNVQUlqV1RNUURXRlFONjQrM3BIc2RGWQpaTHl0ZjlRQmNBMWQ5d0lIeDlyUHNsK0FFeHdIdGhIUTB4SEJmNWRFVXFnM2V5bWlYaUxIMExBNWlINEVHQllJCkFDWVdJUVFZaVZmRGwrVERIc25KaWsrRytLM0lEUHNlVHdVQ1g1dFFjQUliREFVSkFBRlJnQUFLQ1JDRytLM0kKRFBzZVQ1UUZBUDkwV0Vhbldra0Vsd3NwVUtzUVlHRWtKV2Nsa3IyNUlrREdRYXEwdDVxeEZBRUFvbTl2RUlYWQo0dFRGWHFsYS9sWUxzUXJ1RFF5Q0w1VWJBVWVSQ1lQUlNBeWNpd1JmbTJhREVnb3JCZ0VFQVpkVkFRVUJBUWRBCkQ3SFZCakVTaTJRNTFrM0dGT1haL0ZtL2pTZXlNeDBmMGFGZDhwTUZPekVEQVFnSC9nY0RBdnozckQ4aEU5R0oKN1FHOURSbzBvZFdESW5UenllNW1Vd2ZJdVNTSEg5MWpybHQzenN0M2JoQ1BLaDI2NEpRU0RidkdzZDFaTUJXbgpqdEwvSDNpS1ErM2NxbU9XTktQT1kyOFBhMVViOFRpSWZnUVlGZ2dBSmhZaEJCaUpWOE9YNU1NZXljbUtUNGI0CnJjZ00reDVQQlFKZm0yYURBaHNNQlFrQUFWR0FBQW9KRUliNHJjZ00reDVQZGRNQkFLc1RqcGpJYldka3gxbncKK3lqRDNCYllEREF2WW9WUmwvY3NtaVpvT2I2S0FRRDQ2aWI0dDYrTnNVZTVoZFJHamZkdWdVQXhZOUw4cHJGTwovR1FScTlobkNweUxCRitiWndrU0Npc0dBUVFCbDFVQkJRRUJCMEJBNFRoQTd5U1NJaEgzT1JZckx5NFBxc3hoCldsMzNTNDlwWU1HcDdWQTVFQU1CQ0FmK0J3TUMraUxnTXl2bGxkVHRTZXJMUStrQjVyV0FtVWNmZWlUM0JlTzUKWklDN25saDFNZUtOdmNWMTZpNlZpUzQ4ZXNtcDArUDkzVnIzdEpIVjJMeTA2VXo4c01PVFJ4WE9WZTUvYTQrVQoxcS8wOEloK0JCZ1dDQUFtRmlFRUdJbFh3NWZrd3g3SnlZcFBodml0eUF6N0hrOEZBbCtiWndrQ0d3d0ZDUUFCClVZQUFDZ2tRaHZpdHlBejdIaytUZlFEL1hkZzBjRDFsbTRmR3B2Vm9DOVh6dTJxN29FSTZDa1RRNi9sWUE5d0EKTkJVQkFPNmd6M2Rsa1hoNnU4UU1JdWZwOWZ3VjlnbzRHcjFUVUg4bm00cWZiQk1QbklzRVg1dHhOUklLS3dZQgpCQUdYVlFFRkFRRUhRSS9STk1tR0pocWZEbXZianJvQjRLT25vcldPVnhXNzIrcER6clp4eDZrWUF3RUlCLzRICkF3SVdrb0hSUzJFamtPMVBRUklVRHUvUXJXbHNCY2s4dzdaMVZQLzA1Q3h4ai92ZDFPbGo2ajFwRHFveHBMSnAKT0lkNlNmU211TWdaTHBrbTlSaHk1eGpmeHFIYzRGeDlqRDJQUFBta0RkSkNpSDRFR0JZSUFDWVdJUVFZaVZmRApsK1RESHNuSmlrK0crSzNJRFBzZVR3VUNYNXR4TlFJYkRBVUpBQUZSZ0FBS0NSQ0crSzNJRFBzZVQ2SXpBUUNZCkJOeW8yajMxdk9DSFlISWJneUVob2c5T1o1YU9YalJtdFJTUDA0TTVwZ0VBeERZb0dWd3lzajcwZ2hkcC9TZy8KRnpKUnY2dENyUVc1dnp1MXpaNkh0Zzg9Cj1FM1Q4Ci0tLS0tRU5EIFBHUCBQUklWQVRFIEtFWSBCTE9DSy0tLS0tCg=="
          GPG_KEY_GRIP: "E43D94B467AEDD1788FE8DBB3D6409FE49D2CDD1"
          GPG_KEY_PASS: "abc123"

      - name: print testfile
        id: print_testfile
        run: |
          cat test/testfile
