name: functional

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: unlock secrets
        id: unlock_secrets
        uses: someara/action-git-crypt-unlock@main
        env:
          GPG_PRIVATE_KEY: "LS0tLS1CRUdJTiBQR1AgUFJJVkFURSBLRVkgQkxPQ0stLS0tLQoKbERzRVg1dFFjQllKS3dZQkJBSGFSdzhCQVFkQVU0UWJjSlc3Z0pqcy9ya1hjQi9LeU1RS0RNNWU5V2lIbEFsegp1STcwTTVYL0FHVUFSMDVWQWJRZlpHVnRiMnhoWWlBOFpHVnRiMnhoWWtCamIyMXdkWFJsY25NdVltbDZQb2lOCkJCTVdDQUExRmlFRUdJbFh3NWZrd3g3SnlZcFBodml0eUF6N0hrOEZBbCtiVUhBQ0d3TUZDUUFCVVlBQ0N3a0MKRlFnQ0ZnSUNIZ0VDRjRBQUNna1Fodml0eUF6N0hrODZ4d0VBODFkY0NSV1gySE1uaXViY3d0VnR4YUZiRG1lYwpaOENlQitUeU1FellxUUlCQVBJdWJqZG1FclFnd25IZUFSYzdrRkFaL0NwNEtXdXZMMjZnck4yQlowSU9uSXNFClg1dFFjQklLS3dZQkJBR1hWUUVGQVFFSFFIU2pKam9ScHdLYzJ6emt0bi8zOWJ6cGpmNzBmTjhQVkFMdVZrMFoKS2hRTkF3RUlCLzRIQXdJOHdObDBlSDhtQ08xWUNVSGMvQ0toTlBXSXFYYTlMUGx4VGE3bnhGN3h3RTFPaXFwYQpFbXgxdE1lOXRycWk2QmEybndnZFBMZUJkOVdtSnY4MXJ0c2d2ZVVqM1FmK2lndTU1dC9qMFpub2lINEVHQllJCkFDWVdJUVFZaVZmRGwrVERIc25KaWsrRytLM0lEUHNlVHdVQ1g1dFFjQUliREFVSkFBRlJnQUFLQ1JDRytLM0kKRFBzZVQ1UUZBUDkwV0Vhbldra0Vsd3NwVUtzUVlHRWtKV2Nsa3IyNUlrREdRYXEwdDVxeEZBRUFvbTl2RUlYWQo0dFRGWHFsYS9sWUxzUXJ1RFF5Q0w1VWJBVWVSQ1lQUlNBeWNpd1JmbTJhREVnb3JCZ0VFQVpkVkFRVUJBUWRBCkQ3SFZCakVTaTJRNTFrM0dGT1haL0ZtL2pTZXlNeDBmMGFGZDhwTUZPekVEQVFnSC9nY0RBdHlHSWtaNEtNVWkKN1ZFK1FjdVdsRzFtWGllQVdhVTZzL0k1K3lnUTlLNk8wbjZIcytXNXVncEZ4MjE1NGlTbG9yTHRaRVFqN1hPUgpYSEYxTzlFMUNRRWdmcWo4b2lFRG9PVnRXQmhQdWZDSWZnUVlGZ2dBSmhZaEJCaUpWOE9YNU1NZXljbUtUNGI0CnJjZ00reDVQQlFKZm0yYURBaHNNQlFrQUFWR0FBQW9KRUliNHJjZ00reDVQZGRNQkFLc1RqcGpJYldka3gxbncKK3lqRDNCYllEREF2WW9WUmwvY3NtaVpvT2I2S0FRRDQ2aWI0dDYrTnNVZTVoZFJHamZkdWdVQXhZOUw4cHJGTwovR1FScTlobkNweUxCRitiWndrU0Npc0dBUVFCbDFVQkJRRUJCMEJBNFRoQTd5U1NJaEgzT1JZckx5NFBxc3hoCldsMzNTNDlwWU1HcDdWQTVFQU1CQ0FmK0J3TUNLR1JOSCtNWGFYTHRMNUF2VW50YmhST2V5NlIzWkVJU1BoaUsKek9NRkV5OVlBRUt2Yit5QlNyZmxnWDV5Z04ydFFyUGJkaVQ2RFdWODBtbHJwQkNNZEtyQnJHM1NlVkRoUWU3Nwo1b3hPNW9oK0JCZ1dDQUFtRmlFRUdJbFh3NWZrd3g3SnlZcFBodml0eUF6N0hrOEZBbCtiWndrQ0d3d0ZDUUFCClVZQUFDZ2tRaHZpdHlBejdIaytUZlFEL1hkZzBjRDFsbTRmR3B2Vm9DOVh6dTJxN29FSTZDa1RRNi9sWUE5d0EKTkJVQkFPNmd6M2Rsa1hoNnU4UU1JdWZwOWZ3VjlnbzRHcjFUVUg4bm00cWZiQk1QbklzRVg1dHhOUklLS3dZQgpCQUdYVlFFRkFRRUhRSS9STk1tR0pocWZEbXZianJvQjRLT25vcldPVnhXNzIrcER6clp4eDZrWUF3RUlCLzRICkF3SmRhZjlLRkxxcjErMkZ4VE1RWTJadEJ4cWVoanJEVWoxWHRtb09xcmVkUE9KWnFRVmliOVNYMk5GUy8ybFIKRE9sTXpRS3FGZ3BHRGJKc3F2VDNBRGtWTWlxVm03TzdMQU1XZ1FvRVc0K0NpSDRFR0JZSUFDWVdJUVFZaVZmRApsK1RESHNuSmlrK0crSzNJRFBzZVR3VUNYNXR4TlFJYkRBVUpBQUZSZ0FBS0NSQ0crSzNJRFBzZVQ2SXpBUUNZCkJOeW8yajMxdk9DSFlISWJneUVob2c5T1o1YU9YalJtdFJTUDA0TTVwZ0VBeERZb0dWd3lzajcwZ2hkcC9TZy8KRnpKUnY2dENyUVc1dnp1MXpaNkh0ZytjaXdSZm0zSVlFZ29yQmdFRUFaZFZBUVVCQVFkQUQ5eDl3MUdqV0djUApKU1N3Mms4dWM3QVpEdGVORjlZNnhRaFh6aWh0Rm1ZREFRZ0gvZ2NEQXVSeGhjM25oSnFoN1htY0FoYnJ4bTlMCjVNZjVwb1NFbjc5akpCekZOMjhVNlFWUGJVSHZtSnNmWkswdEZTQzdTbFYyV2VpREVSVW93NzZkc3d2Sit2YnQKMC8rTDZEV2daUUtoeFBKK09XaUlmZ1FZRmdnQUpoWWhCQmlKVjhPWDVNTWV5Y21LVDRiNHJjZ00reDVQQlFKZgptM0lZQWhzTUJRa0FBVkdBQUFvSkVJYjRyY2dNK3g1UDU2Y0JBT080aE50MFlCYXdNMjcvTUxHVnl0VVhYZ0pLCnJLWnBoTm9TaURwMmpyejVBUDl2WTN2ekt5cnBSOGJiRDFLRGpOdXpINUQ3dzkwSWt0RWJpYmQwT24vV0NnPT0KPTlzRnAKLS0tLS1FTkQgUEdQIFBSSVZBVEUgS0VZIEJMT0NLLS0tLS0K"
          GPG_KEY_GRIP: "5E499AE750D4DEF10787AC2834A524699842FE6B"
          GPG_KEY_PASS: "abc123"

      - name: print testfile
        id: print_testfile
        run: |
          cat test/testfile
