name: functional

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: unlock secrets
        id: unlock_secrets
        uses: someara/action-git-crypt-unlock@main
        env:
          GPG_PRIVATE_KEY: "lDsEX5tQcBYJKwYBBAHaRw8BAQdAU4QbcJW7gJjs/rkXcB/KyMQKDM5e9WiHlAlzuI70M5X/AGUAR05VAbQfZGVtb2xhYiA8ZGVtb2xhYkBjb21wdXRlcnMuYml6PoiNBBMWCAA1FiEEGIlXw5fkwx7JyYpPhvityAz7Hk8FAl+bUHACGwMFCQABUYACCwkCFQgCFgICHgECF4AACgkQhvityAz7Hk86xwEA81dcCRWX2HMniubcwtVtxaFbDmecZ8CeB+TyMEzYqQIBAPIubjdmErQgwnHeARc7kFAZ/Cp4KWuvL26grN2BZ0IOnIsEX5tQcBIKKwYBBAGXVQEFAQEHQHSjJjoRpwKc2zzktn/39bzpjf70fN8PVALuVk0ZKhQNAwEIB/4HAwKUOT8THiJyTu0RwlYZ2CDAWZGkFhptmhxleu3GTC9lrickhBbkmRn7YOx5FNOPRL7X0u5pi7KbnNjbs9P03mpyojIjjbvXfakqbOORSWCLiH4EGBYIACYWIQQYiVfDl+TDHsnJik+G+K3IDPseTwUCX5tQcAIbDAUJAAFRgAAKCRCG+K3IDPseT5QFAP90WEanWkkElwspUKsQYGEkJWclkr25IkDGQaq0t5qxFAEAom9vEIXY4tTFXqla/lYLsQruDQyCL5UbAUeRCYPRSAyciwRfm2aDEgorBgEEAZdVAQUBAQdAD7HVBjESi2Q51k3GFOXZ/Fm/jSeyMx0f0aFd8pMFOzEDAQgH/gcDAgGty5Ug4J/f7eJgf65zU1S+02GAcXvI5aH7PH8c9NHGOxJb+UENwiGhO5WW4JInAO7gb4vib7krP99sWnY8xjlvCOZA771Ncfbre9ZLD8aIfgQYFggAJhYhBBiJV8OX5MMeycmKT4b4rcgM+x5PBQJfm2aDAhsMBQkAAVGAAAoJEIb4rcgM+x5PddMBAKsTjpjIbWdkx1nw+yjD3BbYDDAvYoVRl/csmiZoOb6KAQD46ib4t6+NsUe5hdRGjfdugUAxY9L8prFO/GQRq9hnCpyLBF+bZwkSCisGAQQBl1UBBQEBB0BA4ThA7ySSIhH3ORYrLy4PqsxhWl33S49pYMGp7VA5EAMBCAf+BwMCmWCUccb2sBjtfTe0L7ApGwOCglKggKgLpHu7UBGkjsnxDhfR1p232OptDblYPeoRv3mQYc3RDOl89LA5HN+ZDgu08FdsEFX4z+CDGTuuXoh+BBgWCAAmFiEEGIlXw5fkwx7JyYpPhvityAz7Hk8FAl+bZwkCGwwFCQABUYAACgkQhvityAz7Hk+TfQD/Xdg0cD1lm4fGpvVoC9Xzu2q7oEI6CkTQ6/lYA9wANBUBAO6gz3dlkXh6u8QMIufp9fwV9go4Gr1TUH8nm4qfbBMPnIsEX5txNRIKKwYBBAGXVQEFAQEHQI/RNMmGJhqfDmvbjroB4KOnorWOVxW72+pDzrZxx6kYAwEIB/4HAwJZu90olVMwWe1fdtsXV0s1PtCTaBhKhZzOwY4GBZ3353hCXDdczF9F3EoxSY44A1TwxwYfpfrzjErxBZ8cJ47NQYPMmPO6MHKykDs4dKO1iH4EGBYIACYWIQQYiVfDl+TDHsnJik+G+K3IDPseTwUCX5txNQIbDAUJAAFRgAAKCRCG+K3IDPseT6IzAQCYBNyo2j31vOCHYHIbgyEhog9OZ5aOXjRmtRSP04M5pgEAxDYoGVwysj70ghdp/Sg/FzJRv6tCrQW5vzu1zZ6Htg+ciwRfm3IYEgorBgEEAZdVAQUBAQdAD9x9w1GjWGcPJSSw2k8uc7AZDteNF9Y6xQhXzihtFmYDAQgH/gcDAt5nGRY9stwt7SFlXDirrZOMlcVpNKJydGzUQzrrfnfoziJIVVDIKoGAM4XOWZQXk8aas1XDeyWI4Eg/RM2/Kp9SkdD38tSe+xS21NMV0iWIfgQYFggAJhYhBBiJV8OX5MMeycmKT4b4rcgM+x5PBQJfm3IYAhsMBQkAAVGAAAoJEIb4rcgM+x5P56cBAOO4hNt0YBawM27/MLGVytUXXgJKrKZphNoSiDp2jrz5AP9vY3vzKyrpR8bbD1KDjNuzH5D7w90IktEbibd0On/WCg=="
          GPG_KEY_GRIP: "5E499AE750D4DEF10787AC2834A524699842FE6B"
          GPG_KEY_PASS: "abc123"

      - name: print testfile
        id: print_testfile
        run: |
          cat test/testfile
