name: functional

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: unlock secrets
        id: unlock_secrets
        uses: someara/action-git-crypt-unlock@main
        env:
          GPG_PRIVATE_KEY: "lIYEX5tQcBYJKwYBBAHaRw8BAQdAU4QbcJW7gJjs/rkXcB/KyMQKDM5e9WiHlAlzuI70M5X+BwMC0LxHnzYEY4ztn45KJ/CNtDDgRWOQaGS4s674h6iJpM1STtdwNH6gMus3giJxgRzf0+tJ3L9BvHOnQGcizeAs5Mp/iOWXf4OZrwSiANB4v7QfZGVtb2xhYiA8ZGVtb2xhYkBjb21wdXRlcnMuYml6PoiNBBMWCAA1FiEEGIlXw5fkwx7JyYpPhvityAz7Hk8FAl+bUHACGwMFCQABUYACCwkCFQgCFgICHgECF4AACgkQhvityAz7Hk86xwEA81dcCRWX2HMniubcwtVtxaFbDmecZ8CeB+TyMEzYqQIBAPIubjdmErQgwnHeARc7kFAZ/Cp4KWuvL26grN2BZ0IOnIsEX5tQcBIKKwYBBAGXVQEFAQEHQHSjJjoRpwKc2zzktn/39bzpjf70fN8PVALuVk0ZKhQNAwEIB/4HAwL33HtER/VIBO2N2XtPGesT/dYsNV2CBixEJBDsdSWqyzv0mg31HpGSqMDFTgxUwtsXlb0JM6NiHJoiUImSMHDaSefjl7phUaFoEkO5sh9LiH4EGBYIACYWIQQYiVfDl+TDHsnJik+G+K3IDPseTwUCX5tQcAIbDAUJAAFRgAAKCRCG+K3IDPseT5QFAP90WEanWkkElwspUKsQYGEkJWclkr25IkDGQaq0t5qxFAEAom9vEIXY4tTFXqla/lYLsQruDQyCL5UbAUeRCYPRSAyciwRfm2aDEgorBgEEAZdVAQUBAQdAD7HVBjESi2Q51k3GFOXZ/Fm/jSeyMx0f0aFd8pMFOzEDAQgH/gcDAhyUzXTs0TmX7bIRwesILrqXocSI4GPwXdS7Mb3dDpuR5w5W9Zzw1KbqY+NpYkfVIctE5KcFUs6vGpmFHFdWh40nqHQ5j01Gwz12Lt7F7HmIfgQYFggAJhYhBBiJV8OX5MMeycmKT4b4rcgM+x5PBQJfm2aDAhsMBQkAAVGAAAoJEIb4rcgM+x5PddMBAKsTjpjIbWdkx1nw+yjD3BbYDDAvYoVRl/csmiZoOb6KAQD46ib4t6+NsUe5hdRGjfdugUAxY9L8prFO/GQRq9hnCpyLBF+bZwkSCisGAQQBl1UBBQEBB0BA4ThA7ySSIhH3ORYrLy4PqsxhWl33S49pYMGp7VA5EAMBCAf+BwMC5YLStujmNhftVZDHEN0L0dMZOwB+b1vZ5W4AktR6UM6XCpQic4HEyz+PSL/QVpnTlX7uunnVtePwh1yWWPAo63ZLde5yxJpp/d/+jDy7s4h+BBgWCAAmFiEEGIlXw5fkwx7JyYpPhvityAz7Hk8FAl+bZwkCGwwFCQABUYAACgkQhvityAz7Hk+TfQD/Xdg0cD1lm4fGpvVoC9Xzu2q7oEI6CkTQ6/lYA9wANBUBAO6gz3dlkXh6u8QMIufp9fwV9go4Gr1TUH8nm4qfbBMPnIsEX5txNRIKKwYBBAGXVQEFAQEHQI/RNMmGJhqfDmvbjroB4KOnorWOVxW72+pDzrZxx6kYAwEIB/4HAwLCRv33cAV7X+1XpLZKN1RwXexRuUXDSGI1Kkr3NmQCusWyqt0olX2vvx7WnRzkXOZuqGgdShCBEp9vYIOySmgV8txLs9aJXTPRcqgLke+iiH4EGBYIACYWIQQYiVfDl+TDHsnJik+G+K3IDPseTwUCX5txNQIbDAUJAAFRgAAKCRCG+K3IDPseT6IzAQCYBNyo2j31vOCHYHIbgyEhog9OZ5aOXjRmtRSP04M5pgEAxDYoGVwysj70ghdp/Sg/FzJRv6tCrQW5vzu1zZ6Htg+ciwRfm3IYEgorBgEEAZdVAQUBAQdAD9x9w1GjWGcPJSSw2k8uc7AZDteNF9Y6xQhXzihtFmYDAQgH/gcDAtqnntg7EedV7ZSTqZxvpGBIjd8XjKtgV3MEOvZqLvoSfmjINLQ8O0yr2QK8l3yr40dQIvUdEKM+11wu/P4we7BHs3/6tBSC//5HEaM0KqWIfgQYFggAJhYhBBiJV8OX5MMeycmKT4b4rcgM+x5PBQJfm3IYAhsMBQkAAVGAAAoJEIb4rcgM+x5P56cBAOO4hNt0YBawM27/MLGVytUXXgJKrKZphNoSiDp2jrz5AP9vY3vzKyrpR8bbD1KDjNuzH5D7w90IktEbibd0On/WCpyLBF+bdw0SCisGAQQBl1UBBQEBB0BKStMoftHoEOnY2XvbMZYNCf11NFj8xa3CmyJPqadbIgMBCAf+BwMCToDvM3Ccl+ft5Ei1MEONUpk5EQ+kQWmEcAqFx0CAeOruAcbplH9OjA7JFWCofiVNdkYNRbgSB0yCMaoi8GgmwuUh6iaiFC/P2ysEHX3RVIh+BBgWCAAmFiEEGIlXw5fkwx7JyYpPhvityAz7Hk8FAl+bdw0CGwwFCQABUYAACgkQhvityAz7Hk8zLQEAuEv1RAXJIGiLrGZUFDOJ5XbpmFJ7Pd0LOKBJ8XhanawA/0BoBPQBj4QbyuwftkpAnlub+TKVAdQSaJqkL7fWCFED"
          GPG_KEY_GRIP: "9304F8E2BCC519F2431FD4B8F10734FA9B9552AD"
          GPG_KEY_PASS: "abc123"

      - name: print testfile
        id: print_testfile
        run: |
          cat test/testfile
