name: functional

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: unlock secrets
        id: unlock_secrets
        uses: someara/action-git-crypt-unlock@main
        env:
          GPG_PRIVATE_KEY: "LS0tLS1CRUdJTiBQR1AgUFJJVkFURSBLRVkgQkxPQ0stLS0tLQoKbElZRVg1dFFjQllKS3dZQkJBSGFSdzhCQVFkQVU0UWJjSlc3Z0pqcy9ya1hjQi9LeU1RS0RNNWU5V2lIbEFsegp1STcwTTVYK0J3TUN3QXRPcnE5RlE4THRiK25sVW9rRTBFOXpFdDdtR3hqckJ6M1B2N3BnZ1pvL2dSVnBkSVBXCmpsdWRPTnRDNjZWVnBFMUdHRUtzVlg4S2U0Y3Q5WnY0TmptWEdmVmdWTzRsQkFxWk1FWDJKclFmWkdWdGIyeGgKWWlBOFpHVnRiMnhoWWtCamIyMXdkWFJsY25NdVltbDZQb2lOQkJNV0NBQTFGaUVFR0lsWHc1Zmt3eDdKeVlwUApodml0eUF6N0hrOEZBbCtiVUhBQ0d3TUZDUUFCVVlBQ0N3a0NGUWdDRmdJQ0hnRUNGNEFBQ2drUWh2aXR5QXo3CkhrODZ4d0VBODFkY0NSV1gySE1uaXViY3d0VnR4YUZiRG1lY1o4Q2VCK1R5TUV6WXFRSUJBUEl1YmpkbUVyUWcKd25IZUFSYzdrRkFaL0NwNEtXdXZMMjZnck4yQlowSU9uSXNFWDV0UWNCSUtLd1lCQkFHWFZRRUZBUUVIUUhTagpKam9ScHdLYzJ6emt0bi8zOWJ6cGpmNzBmTjhQVkFMdVZrMFpLaFFOQXdFSUIvNEhBd0lLMUgwQW9IdnU2ZTBaClBNSk1VSkRucHdSY2Y3YTNvY0NCQVNZd2dOZktBbVo4b0xSOHJEOFByRVZKbE90TCtRYzZqOU52QTV2N2dNMFoKR05uOVRZTzF5akN0NzRndnpXL0YzVlhJU0pmVmlINEVHQllJQUNZV0lRUVlpVmZEbCtUREhzbkppaytHK0szSQpEUHNlVHdVQ1g1dFFjQUliREFVSkFBRlJnQUFLQ1JDRytLM0lEUHNlVDVRRkFQOTBXRWFuV2trRWx3c3BVS3NRCllHRWtKV2Nsa3IyNUlrREdRYXEwdDVxeEZBRUFvbTl2RUlYWTR0VEZYcWxhL2xZTHNRcnVEUXlDTDVVYkFVZVIKQ1lQUlNBdz0KPUdYK3QKLS0tLS1FTkQgUEdQIFBSSVZBVEUgS0VZIEJMT0NLLS0tLS0K"
          GPG_KEY_GRIP: "188957C397E4C31EC9C98A4F86F8ADC80CFB1E4F"
          GPG_KEY_PASS: "abc123"

      - name: print unencrypted testfile
        id: print_unencrypted
        run: |
          cat test/testfile
